<?php

/**
 * @file
 * Main helper functions for Carter website accessibility.
 */

use Bluecadet\DrupalPackageManager\Checker;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_update_status_alter().
 */
function bluecadet_accessibility_update_status_alter(&$projects) {

  $modules['bluecadet'] = [
    'bluecadet_accessibility',
  ];

  $filtered_projects = [];

  foreach ($modules as $user => $user_data) {
    $filtered_projects += array_filter($projects, function ($v) use ($user_data) {
        return in_array($v, $user_data);
    }, ARRAY_FILTER_USE_KEY);
  }

  $checker = new Checker($modules, $filtered_projects);

  foreach ($modules as $user => $user_data) {
    foreach ($user_data as $module_name) {
      if (in_array($module_name, array_keys($projects))) {
        $projects[$module_name] = $checker->updateDrupalModulePackage($projects[$module_name], $user, $module_name);
      }
    }
  }
}

/**
 * Implements hook_form_views_pre_render().
 *
 * Add instance dates to view results.
 */
function bluecadet_accessibility_views_pre_render(ViewExecutable $view) {

  // Grab the options set on the view display.
  $display_extenders_options = $view->display_handler->getOption('display_extenders');
  if (
    (
      $view->ajaxEnabled() &&
      (
        isset($display_extenders_options['ajax_ally_option']['enable_ally']) &&
        $display_extenders_options['ajax_ally_option']['enable_ally'] == TRUE
      )
    ) &&
    empty($view->is_attachment) && empty($view->live_preview)
  ) {

    // Attach the library.
    $view->element['#attached']['library'][] = 'bluecadet_accessibility/viewsAjaxA11y';
  }
}
